FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Linux64"
RecentFilesList = ["d:\\Beef-Net\\src\\MimeList.bf", "src\\HttpUtil.bf", "src\\HttpClient.bf", "src\\Http.bf", "src\\HttpServer.bf"]

[MainWindow]
X = 754
Y = 117
Width = 1166
Height = 589
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 201.0
RequestedHeight = 248.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 109.8214
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 398.0
SizePriority = 250.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "MimeList.bf"
TabWidth = 102.6786
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "d:\\Beef-Net\\src\\MimeList.bf"
CursorPos = 818
VertPos = 518.075
ProjectName = "Beef-Net"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "HttpUtil.bf"
TabWidth = 96.42857
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\HttpUtil.bf"
CursorPos = 86
ProjectName = "Beef-Http-Server"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "HttpClient.bf"
TabWidth = 108.9286
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\HttpClient.bf"
CursorPos = 41
ProjectName = "Beef-Http-Server"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Http.bf"
TabWidth = 77.67857
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Http.bf"
CursorPos = 110
ProjectName = "Beef-Http-Server"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "HttpServer.bf"
TabWidth = 110.7143
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\HttpServer.bf"
CursorPos = 50
ProjectName = "Beef-Http-Server"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 248.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Errors"
TabWidth = 82.14286
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 96.42857
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 84.82143
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 224.0}, {Width = 224.0}, {Width = 224.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 76.78571
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 224.0}, {Width = 224.0}, {Width = 224.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 0.5
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 92.85714
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 101.7857
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 108.0357
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.17857
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
