FileVersion = 1
Projects = {Beef-Http-Server = {Path = "."}, Beef-Net = {Path = "../Beef-Net"}, Beef-OpenSSL = {Path = "../Beef-Net/Beef-OpenSSL"}}
ExtraPlatforms = ["Linux64"]

[Workspace]
StartupProject = "Beef-Http-Server"
